builds:
  - binary: funnel-plugins
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags: >
      -X github.com/ohsu-comp-bio/funnel-plugins/version.BuildDate={{.Date}}
      -X github.com/ohsu-comp-bio/funnel-plugins/version.GitCommit={{.ShortCommit}}
      -X github.com/ohsu-comp-bio/funnel-plugins/version.GitBranch={{.Env.GIT_BRANCH}}
      -X github.com/ohsu-comp-bio/funnel-plugins/version.GitUpstream={{.Env.GIT_UPSTREAM}}
      -X github.com/ohsu-comp-bio/funnel-plugins/version.Version={{.Version}}

dist: build/release

release:
  draft: true

env_files:
  github_token: .github_token

archives:
  - format: tar.gz
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}-{{.Version}}"
