name: Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v3
      with:
        go-version: 'stable'

    - name: Test
      run: |
        make

        ./server &
        
        curl --header "Authorization: Bearer Alyssa P. Hacker" \
             --data @example-tasks/hello-world.json \
             http://localhost:8080

        curl --header "Authorization: Bearer Foo" \
             --data @example-tasks/hello-world.json \
             http://localhost:8080
